package src.shelter;

public enum CatBreed {
	PERSAIN,MAINECOON,BENGAL,BRITISHSHORTHAIR,SIAMESE,SPHYNX,RAGDOLL,MUNCHKIN,SCOTTISHFOLD,NORWEGIANFOREST,SAVANNAH,SIBERIAN,AMERICANSHORTHAIR,HIMALAYAN,ABYSSININA,BIRMAN,CHARTREUX;
}